index:
    path: /
    controller: App\Controller\UserController::signUp

user_sign_up:
    path: /sign-up
    controller: App\Controller\UserController::signUp

user_sign_up_handler:
    path: /sign-up-handler
    controller: App\Controller\UserController::signUpHandler
    methods: POST

user_sign_up_step1:
    path: /sign-up/step1
    controller: App\Controller\UserController::handleStep1
    methods: POST

user_sign_up_step2:
    path: /sign-up/step2
    controller: App\Controller\UserController::handleStep2
    methods: POST

user_sign_up_step3:
    path: /sign-up/step3
    controller: App\Controller\UserController::handleStep3
    methods: POST

fetch_saved_data:
    path: /sign-up/fetch-saved-data
    controller: App\Controller\UserController::fetchSavedData

clear_session:
    path: /sign-up/clear-session
    controller: App\Controller\UserController::clearSession